/** app */
export const APP_READY = 'APP_READY'
export const APP_RESIZE_START = 'APP_RESIZE_START'
export const APP_RESIZE_STOP = 'APP_RESIZE_STOP'
export const APP_SET_SIZE = 'APP_SET_SIZE'
export const APP_SCROLL_START = 'APP_SCROLL_START'
export const APP_SET_SCROLL_DIRECTION = 'APP_SET_SCROLL_DIRECTION'
export const APP_SCROLL_STOP = 'APP_SCROLL_STOP'
export const APP_SET_SCROLL_Y = 'APP_SET_SCROLL_Y'
export const APP_ADD_HEARTBEAT = 'APP_ADD_HEARTBEAT'
export const APP_REMOVE_HEARTBEAT = 'APP_REMOVE_HEARTBEAT'
export const APP_CHANGE_LOCALE = 'APP_CHANGE_LOCALE'

/** header */
export const HEADER_READY = 'HEADER_READY'
export const HEADER_HIDE = 'HEADER_HIDE'
export const HEADER_SHOW = 'HEADER_SHOW'
export const HEADER_SET_BACKGROUND = 'HEADER_SET_BACKGROUND'

/** sidebar */
export const SIDEBARS_READY = 'SIDEBARS_READY'
export const SIDEBARS_HIDE = 'SIDEBARS_HIDE'
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE'

/** core */
export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'

/** account */
export const ACCOUNT_READY = 'ACCOUNT_READY'
export const ACCOUNT_SWITCH_FORMS = 'ACCOUNT_SWITCH_FORMS'
export const ACCOUNT_TOGGLE_REGISTRATION = 'ACCOUNT_TOGGLE_REGISTRATION'
export const ACCOUNT_TOGGLE_MENU = 'ACCOUNT_TOGGLE_MENU'
export const ACCOUNT_CLEAR_PASSWORDS = 'ACCOUNT_CLEAR_PASSWORDS'
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const CLEAR_AUTHENTICATION_ERROR = 'CLEAR_AUTHENTICATION_ERROR'
export const SUBMIT_LOGOUT = 'SUBMIT_LOGOUT'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

/** notification */
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD'
export const NOTIFICATION_SET_STATUS = 'NOTIFICATION_SET_STATUS'
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE'
export const NOTIFICATIONS_TOGGLE = 'NOTIFICATIONS_TOGGLE'
export const NOTIFICATIONS_STATS_TOGGLE = 'NOTIFICATIONS_STATS_TOGGLE'
export const NOTIFICATIONS_SET_FILTER = 'NOTIFICATIONS_SET_FILTER'
export const NOTIFICATION_REMOVE_FROM_ACTIVE = 'NOTIFICATION_REMOVE_FROM_ACTIVE'

/** calendar */
export const CALENDAR_SET_CURRENT_YEAR = 'CALENDAR_SET_CURRENT_YEAR'
export const CALENDAR_SET_CURRENT_MONTH = 'CALENDAR_SET_CURRENT_MONTH'
export const CALENDAR_SET_CURRENT_DAY = 'CALENDAR_SET_CURRENT_DAY'
